swagger: '2.0'
info:
  description: This is the swagger definition for a made up application
  version: 1.1.1
  title: Example
  contact:
    email: john-carmichael@email.it
schemes:
  - http
  - https
host: 'https://ieezih6v9i.execute-api.eu-central-1.amazonaws.com/int'
basePath: /api/v1
tags:
  - name: weather
    description: Weather data
paths:
  '/weather/{country}':
    get:
      tags:
        - weather
      summary: Weather data
      description: Weather for a given country for a given `ISO ALPHA-2 Code'
      operationId: weatherShow
      produces:
        - application/json
      parameters:
        - in: path
          name: country
          description: ISO "ALPHA-2 Code"
          required: true
          type: string
      responses:
        '200':
          description: Successful fecth
          schema:
            $ref: '#/definitions/Weather'
        '404':
          description: Country not found
  /temperature/:
    get:
      tags:
        - temperature
      summary: Temperature data
      description: Get the latest temperature
      operationId: temperatureLatestShow
      produces:
        - application/json
      responses:
        '200':
          description: Successful fetch
          schema:
            $ref: '#/definitions/Temperature'
        '404':
          description: Temp not found
    post:
      tags:
        - temperature
      summary: Temperature data
      description: Create a new temperature record.
      operationId: temperatureLatestShow
      produces:
        - application/json
      parameters:
        - in: body
          name: temp
          description: Temp to create
          schema:
            type: object
            required:
              - temp
            properties:
              temp:
                type: number
      responses:
        '200':
          description: Successful temp creation
          schema:
            $ref: '#/definitions/Temperature'
        '422':
          description: Invalid form data provided
definitions:
  Temperature:
    type: object
    properties:
      data:
        type: array
        items:
          title: Temp
          type: object
          properties:
            type:
              type: string
            id:
              type: string
            attributes:
              degrees:
                type: string
              date:
                type: string
  Weather:
    type: object
    properties:
      data:
        type: array
        items:
          title: Weather
          type: object
          properties:
            type:
              type: string
            id:
              type: string
            attributes:
              cloudCover:
                type: string
              humidity:
                type: number
              precipitation:
                type: number
              temperature:
                $ref: '#/definitions/UnitNumericAttributes'
              windSpeed:
                $ref: '#/definitions/UnitNumericAttributes'
              windDirection:
                $ref: '#/definitions/UnitNumericAttributes'
  UnitNumericAttributes:
    type: array
    items:
      type: object
      properties:
        unit:
          type: string
        value:
          type: number
